run_name: nwm_cdit_s-topo

# training setup
results_dir: checkpoints/cdit/res128
train: True
batch_size: 8
num_workers: 4
model: CDiT-S/2
lr: 2e-5

# normalization for the action space
normalize: True
grad_clip_val: 10.0
context_size: 1

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: -16
  max_dist_cat: 16

# action output params
len_traj_pred: 16

# dataset specific parameters
image_size: 128
datasets:
  nav2d1:
    data_folder: /mnt/d/datasets/nav2d/dataset1
    train: data_splits/nav2d1/train/
    test: data_splits/nav2d1/test/
    goals_per_obs: 4
  # recon:
  #   data_folder: data/recon
  #   train: data_splits/recon/train/ # path to train folder with traj_names.txt
  #   test: data_splits/recon/test/ # path to test folder with traj_names.txt
  #   goals_per_obs: 4
  # tartan_drive:
  #   data_folder: data/tartan
  #   train: data_splits/tartan_drive/train/
  #   test: data_splits/tartan_drive/test/
  #   goals_per_obs: 4
  # sacson:
  #   data_folder: data/sacson
  #   train: data_splits/sacson/train
  #   test: data_splits/sacson/test
  #   goals_per_obs: 4
  # scand:
  #   data_folder: data/scand
  #   train: data_splits/scand/train
  #   test: data_splits/scand/test
  #   goals_per_obs: 4
